"""
Pydantic models for API requests.
These define the contract between the API and external clients.

Following clean architecture principles, request models delegate validation
to domain model class methods and reuse field descriptions to avoid
duplication while maintaining single source of truth in the domain layer.
"""

from datetime import UTC, datetime
from typing import Any

from julee.core.values.text import Name, NonEmptyText
from pydantic import BaseModel, Field, ValidationInfo, field_validator

from julee_ceap.domain.models.assembly_specification.assembly_specification import (
    AssemblySpecification,
    AssemblySpecificationStatus,
    refuse_a_bad_pointer,
    refuse_a_bad_schema,
)
from julee_ceap.domain.models.assembly_specification.knowledge_service_query import (
    KnowledgeServiceQuery,
)
from julee_ceap.domain.values.query_metadata import QueryMetadata
from julee_ceap.domain.values.schema import JsonSchema


class CreateAssemblySpecificationRequest(BaseModel):
    """Request model for creating an assembly specification.

    This model defines what clients need to provide when creating a new
    assembly specification. Validation logic is delegated to the domain
    model to ensure consistency and avoid duplication.

    Fields excluded from client control:
    - assembly_specification_id: Always generated by the server
    - status: Always set to DRAFT initially by the server
    - created_at/updated_at: System-managed timestamps
    """

    # These descriptions were read off AssemblySpecification.model_fields,
    # which a frozen dataclass does not have. They are written here now,
    # which is where they belong: this is the message, and what a client
    # is told about a field it sends is the message's business.
    name: Name = Field(description="Human-readable name like 'meeting minutes'")
    applicability: NonEmptyText = Field(
        description=(
            "Text description identifying to what type of information this "
            "assembly applies, such as an online transcript of a video "
            "meeting. This information may be used by knowledge service for "
            "document-assembly matching"
        )
    )
    jsonschema: dict[str, Any] = Field(
        description=(
            "JSON Schema defining the structure of data to be extracted "
            "for this assembly"
        )
    )
    knowledge_service_queries: dict[str, NonEmptyText] = Field(
        default_factory=dict,
        description=(
            "Mapping from JSON Pointer paths to KnowledgeServiceQuery IDs. "
            "Keys are JSON Pointer strings (e.g., '/properties/attendees', "
            "'') and values are query IDs for extracting data for that "
            "schema section"
        ),
    )
    version: NonEmptyText = Field(
        default=NonEmptyText("0.1.0"),
        description="Assembly definition version",
    )

    # The rules that are a field's shape travel with its type now.
    # What is left here are the two that are not: a JSON Schema
    # that has to compile, and queries that have to name real
    # ones (#71).
    @field_validator("jsonschema")
    @classmethod
    def validate_jsonschema(cls, v: dict[str, Any]) -> dict[str, Any]:
        refuse_a_bad_schema(v)
        return v

    @field_validator("knowledge_service_queries")
    @classmethod
    def validate_knowledge_service_queries(
        cls, v: dict[str, NonEmptyText], info: ValidationInfo
    ) -> dict[str, NonEmptyText]:
        schema = info.data.get("jsonschema")
        if schema is not None:
            refuse_a_bad_pointer(v, schema)
        return v

    def to_domain_model(self, assembly_specification_id: str) -> AssemblySpecification:
        """Convert this request to a complete AssemblySpecification object.

        Args:
            assembly_specification_id: The ID to assign to the new spec

        Returns:
            AssemblySpecification: Complete domain object with system fields
        """
        now = datetime.now(UTC)
        return AssemblySpecification(
            assembly_specification_id=NonEmptyText(assembly_specification_id),
            name=self.name,
            applicability=self.applicability,
            jsonschema=JsonSchema(self.jsonschema),
            knowledge_service_queries=self.knowledge_service_queries,
            version=self.version,
            status=AssemblySpecificationStatus.DRAFT,
            created_at=now,
            updated_at=now,
        )


class QueryMetadataRequest(BaseModel):
    """How a query asks to be run, on the wire.

    The domain's QueryMetadata is a frozen dataclass; this is its
    message form. It was ``dict[str, Any]``, so the OpenAPI schema said
    only "object" and a client had to read the prose to learn what went
    in it. The three knobs are named and typed now, and a response
    carries all three, with null for a knob the query left unset.

    Extra keys are still ignored rather than refused, as everywhere else
    in this API — no request model here sets ``extra="forbid"``, and
    changing that is an API policy decision, not part of naming a type.
    """

    model: str | None = Field(
        default=None, description="Which model to use, or omit for the service's"
    )
    max_tokens: int | None = Field(
        default=None, description="Token budget for the response, or omit"
    )
    temperature: float | None = Field(
        default=None, description="How much the response may vary, or omit"
    )

    def to_domain_model(self) -> QueryMetadata:
        """Build the domain value this message stands for.

        Returns:
            QueryMetadata: what the domain speaks
        """
        return QueryMetadata(
            model=self.model,
            max_tokens=self.max_tokens,
            temperature=self.temperature,
        )


class CreateKnowledgeServiceQueryRequest(BaseModel):
    """Request model for creating a knowledge service query.

    This model defines what clients need to provide when creating a new
    knowledge service query. Validation logic is delegated to the domain
    model and descriptions are reused to avoid duplication while maintaining
    single source of truth in the domain layer.

    Fields excluded from client control:
    - query_id: Always generated by the server
    - created_at/updated_at: System-managed timestamps
    """

    # Written here rather than read off KnowledgeServiceQuery.model_fields,
    # for the reason given above.
    name: Name = Field(description="Human-readable name describing the query purpose")
    knowledge_service_id: NonEmptyText = Field(
        description="Identifier of the knowledge service to query"
    )
    prompt: NonEmptyText = Field(
        description=(
            "The specific prompt to send to the knowledge service for this extraction"
        )
    )
    query_metadata: QueryMetadataRequest = Field(
        default_factory=lambda: QueryMetadataRequest(),
        description="How this query asks to be run. Omitted knobs are the service's",
    )
    assistant_prompt: str | None = Field(
        default=None,
        description=(
            "Optional assistant message content to constrain or prime the "
            "model's response. This is added as the final assistant message "
            "before the model generates its response, allowing control over "
            "response format and structure"
        ),
    )

    # The rules that are a field's shape travel with its type now.
    # What is left here are the two that are not: a JSON Schema
    # that has to compile, and queries that have to name real
    # ones (#71).
    def to_domain_model(self, query_id: str) -> KnowledgeServiceQuery:
        """Convert this request to a complete KnowledgeServiceQuery object.

        Args:
            query_id: The ID to assign to the new query

        Returns:
            KnowledgeServiceQuery: Complete domain object with system fields
        """
        now = datetime.now(UTC)
        return KnowledgeServiceQuery(
            query_id=NonEmptyText(query_id),
            name=self.name,
            knowledge_service_id=self.knowledge_service_id,
            prompt=self.prompt,
            query_metadata=self.query_metadata.to_domain_model(),
            assistant_prompt=self.assistant_prompt,
            created_at=now,
            updated_at=now,
        )
